### ISSUE TITLE
The backup works only for user pi.

### ISSUE THREAD

**Issue by Hollywood64** [justinpearson/Raspberry-Pi-for-iPhone-Backup#2]
The backup works only for user pi.

The $HOME environment variable should be used instead.

**Comment by justinpearson** [comment]
Thanks for the comment! I took at stab at removing the dependence on user `pi`, but it's tricky to get `$HOME` to work right in udev. Take a look and send me a Pull Request if you like!: https://github.com/justinpearson/Raspberry-Pi-for-iPhone-Backup/commit/8d50a5965bee2fe7e02dd4428129ffdd68121c96
