### ISSUE TITLE
It does not work for an iPad!!!

### ISSUE THREAD

**Issue by Hollywood64** [justinpearson/Raspberry-Pi-for-iPhone-Backup#3]
the backup_iphone.py looks for iPhone in line 96

instead using 
   return 'iPhone' in p.stdout
you should use
   return 'iPad' in p.stdout or 'iPhone' in p.stdout

It wuould work for iPads and for iPhones with this change.

**Comment by justinpearson** [comment]
Fixed! Thanks.
https://github.com/justinpearson/Raspberry-Pi-for-iPhone-Backup/commit/001bc4e6e03599934b251bf75bc8fec73d6238b9
